#! /usr/bin/env python3
from my_secrets import *
from chatgpt import *
import json, sys

monster_list = [
    # "Aarakocra",
    # "Aboleth",
    # "Abominable Yeti",
    # "Acolyte",
    # "Adult Black Dragon",
    # "Adult Blue Dracolich",
    # "Adult Blue Dragon",
    # "Adult Brass Dragon",
    # "Adult Bronze Dragon",
    # "Adult Copper Dragon",
    # "Adult Gold Dragon",
    # "Adult Green Dragon",
    # "Adult Red Dragon",
    # "Adult Silver Dragon",
    # "Adult White Dragon",
    # "Air Elemental",
    # "Allosaurus",
    # "Ancient Black Dragon",
    # "Ancient Blue Dragon",
    # "Ancient Brass Dragon",
    # "Ancient Bronze Dragon",
    # "Ancient Copper Dragon",
    # "Ancient Gold Dragon",
    # "Ancient Green Dragon",
    # "Ancient Red Dragon",
    # "Ancient Silver Dragon",
    # "Ancient White Dragon",
    # "Androsphinx",
    # "Animated Armor",
    # "Ankheg",
    # "Ankylosaurus",
    # "Ape",
    # "Arcanaloth",
    # "Archmage",
    # "Assassin",
    # "Awakened Shrub",
    # "Awakened Tree",
    # "Axe Beak",
    # "Azer",
    # "Baboon",
    # "Badger",
    # "Balor",
    # "Bandit",
    # "Bandit Captain",
    # "Banshee",
    # "Barbed Devil",
    # "Barlgura",
    # "Basilisk",
    # "Bat",
    # "Bearded Devil",
    # "Behir",
    # "Beholder",
    # "Beholder Zombie",
    # "Berserker",
    # "Black Bear",
    # "Black Dragon Wyrmling",
    # "Black Pudding",
    # "Blink Dog",
    # "Blood Hawk",
    # "Blue Dragon Wyrmling",
    # "Blue Slaad",
    # "Boar",
    # "Bone Devil",
    # "Bone Naga",
    # "Brass Dragon Wyrmling",
    # "Bronze Dragon Wyrmling",
    # "Brown Bear",
    # "Bugbear",
    # "Bugbear Chief",
    # "Bulette",
    # "Bullywug",
    # "Cambion",
    # "Camel",
    # "Carrion Crawler",
    # "Cat",
    # "Centaur",
    # "Chain Devil",
    # "Chasme",
    # "Chimera",
    # "Chuul",
    # "Clay Golem",
    # "Cloaker",
    # "Cloud Giant",
    # "Cockatrice",
    # "Commoner",
    # "Constrictor Snake",
    # "Copper Dragon Wyrmling",
    # "Couatl",
    # "Crab",
    # "Crawling Claw",
    # "Crocodile",
    # "Cult Fanatic",
    # "Cultist",
    # "Cyclops",
    # "Dao",
    # "Darkmantle",
    # "Death Dog",
    # "Death Knight",
    # "Death Slaad",
    # "Death Tyrant",
    # "Deep Gnome (Svirfneblin)",
    # "Deer",
    # "Demilich",
    # "Deva",
    # "Dire Wolf",
    # "Displacer Beast",
    # "Djinni",
    # "Doppelganger",
    # "Draft Horse",
    # "Dragon Turtle",
    # "Dretch",
    # "Drider",
    # "Drow",
    # "Drow Elite Warrior",
    # "Drow Mage",
    # "Drow Priestess of Lolth",
    # "Druid",
    # "Dryad",
    # "Duergar",
    # "Duodrone",
    # "Dust Mephit",
    # "Eagle",
    # "Earth Elemental",
    # "Efreeti",
    # "Elephant",
    # "Elk",
    # "Empyrean",
    # "Erinyes",
    # "Ettercap",
    # "Ettin",
    # "Faerie Dragon",
    # "Fire Elemental",
    # "Fire Giant",
    # "Fire Snake",
    # "Flameskull",
    # "Flesh Golem",
    # "Flumph",
    # "Flying Snake",
    # "Flying Sword",
    # "Fomorian",
    # "Frog",
    # "Frost Giant",
    # "Galeb Duhr",
    # "Gargoyle",
    # "Gas Spore",
    # "Gelatinous Cube",
    # "Ghast",
    # "Ghost",
    # "Ghoul",
    # "Giant Ape",
    # "Giant Badger",
    # "Giant Bat",
    # "Giant Boar",
    # "Giant Centipede",
    # "Giant Constrictor Snake",
    # "Giant Crab",
    # "Giant Crocodile",
    # "Giant Eagle",
    # "Giant Elk",
    # "Giant Fire Beetle",
    # "Giant Frog",
    # "Giant Goat",
    # "Giant Hyena",
    # "Giant Lizard",
    # "Giant Octopus",
    # "Giant Owl",
    # "Giant Poisonous Snake",
    # "Giant Rat",
    # "Giant Scorpion",
    # "Giant Sea Horse",
    # "Giant Shark",
    # "Giant Spider",
    # "Giant Toad",
    # "Giant Vulture",
    # "Giant Wasp",
    # "Giant Weasel",
    # "Giant Wolf Spider",
    # "Giant Hyena",
    # "Giant Lizard",
    # "Giant Octopus",
    # "Giant Owl",
    # "Giant Poisonous Snake",
    # "Giant Rat",
    # "Giant Scorpion",
    # "Giant Sea Horse",
    # "Giant Shark",
    # "Giant Spider",
    # "Giant Toad",
    # "Giant Vulture",
    # "Giant Wasp",
    # "Giant Weasel",
    # "Giant Wolf Spider",
    # "Gibbering Mouther",
    # "Glabrezu",
    # "Gladiator",
    # "Gnoll",
    # "Gnoll Fang of Yeenoghu",
    # "Gnoll Pack Lord",
    # "Goat",
    # "Goblin",
    # "Goblin Boss",
    # "Gold Dragon Wyrmling",
    # "Gorgon",
    # "Gray Ooze",
    # "Green Dragon Wyrmling",
    # "Green Hag",
    # "Griffon",
    # "Grimlock",
    # "Guard",
    # "Guardian Naga",
    # "Gynosphinx",
    # "Half-Red Dragon Veteran",
    # "Harpy",
    # "Hawk",
    # "Hezrou",
    # "Hill Giant",
    # "Hippogriff",
    # "Hobgoblin",
    # "Hobgoblin Captain",
    # "Hobgoblin Warlord",
    # "Homunculus",
    # "Horned Devil",
    # "Hunter Shark",
    # "Hydra",
    # "Hyena",
    # "Ice Devil",
    # "Ice Mephit",
    # "Imp",
    # "Intellect Devourer",
    # "Invisible Stalker",
    # "Iron Golem",
    # "Jackal",
    # "Killer Whale",
    # "Knight",
    # "Kobold",
    # "Kraken",
    # "Lamia",
    # "Lemure",
    # "Lich",
    # "Lizard",
    # "Lizardfolk",
    # "Lizardfolk Shaman",
    # "Mage",
    # "Magma Mephit",
    # "Magmin",
    # "Mammoth",
    # "Manticore",
    # "Marilith",
    # "Mastiff",
    # "Medusa",
    # "Merfolk",
    # "Merrow",
    # "Mezzoloth",
    # "Mimic",
    # "Minotaur",
    # "Minotaur Skeleton",
    # "Mule",
    # "Mummy",
    # "Mummy Lord",
    # "Myconid Adult",
    # "Myconid Sovereign",
    # "Myconid Sprout",
    # "Nalfeshnee",
    # "Noble",
    # "Ochre Jelly",
    # "Octopus",
    # "Ogre",
    # "Ogre Zombie",
    # "Oni",
    # "Orc",
    # "Orog",
    # "Otyugh",
    # "Owl",
    # "Owlbear",
    # "Pegasus",
    # "Pentadrone",
    # "Peryton",
    # "Pirate",
    # "Pixie",
    # "Planetar",
    # "Plesiosaurus",
    # "Poisonous Snake",
    # "Polar Bear",
    # "Pony",
    # "Priest",
    # "Pseudodragon",
    # "Pterydactyl",
    # "Purple Worm",
    # "Quasit",
    # "Quipper",
    # "Rakshasa",
    # "Rat",
    # "Raven",
    # "Red Dragon Wyrmling",
    # "Reef Shark",
    # "Remorhaz",
    # "Rhinoceros",
    # "Riding Horse",
    # "Roc",
    # "Roper",
    # "Rug of Smothering",
    # "Rust Monster",
    # "Saber-Toothed Tiger",
    # "Sahuagin",
    # "Sahuagin Baron",
    "Sahuagin Priestess",
    "Salamander",
    "Satyr",
    "Scorpion",
    "Scout",
    "Sea Hag",
    "Sea Horse",
    "Shadow",
    "Shambling Mound",
    "Shield Guardian",
    "Shrieker",
    "Silver Dragon Wyrmling",
    "Skeleton",
    "Solar",
    "Specter",
    "Spider",
    "Spirit Naga",
    "Sprite",
    "Spy",
    "Steam Mephit",
    "Stirge",
    "Stone Giant",
    "Stone Golem",
    "Storm Giant",
    "Succubus/Incubus",
    "Swarm of Bats",
    "Swarm of Bees",
    "Swarm of Centipedes",
    "Swarm of Insects",
    "Swarm of Poisonous Snakes",
    "Swarm of Quippers",
    "Swarm of Rats",
    "Swarm of Ravens",
    "Swarm of Spiders",
    "Swarm of Wasps",
    "Tarrasque",
    "Thug",
    "Tiger",
    "Treant",
    "Tribal Warrior",
    "Triceratops",
    "Troglodyte",
    "Troll",
    "Tyrannosaurus Rex",
    "Ultroloth",
    "Umber Hulk",
    "Unicorn",
    "Vampire",
    "Vampire Spawn",
    "Veteran",
    "Violet Fungus",
    "Vrock",
    "Vulture",
    "Warhorse",
    "Warhorse Skeleton",
    "Water Elemental",
    "Weasel",
    "Werebear",
    "Wereboar",
    "Wererat",
    "Weretiger",
    "Werewolf",
    "White Dragon Wyrmling",
    "Wight",
    "Will-o'-Wisp",
    "Winter Wolf",
    "Wolf",
    "Worg",
    "Wraith",
    "Wyvern",
    "Xorn",
    "Yeti",
    "Yuan-ti Abomination",
    "Yuan-ti Malison",
    "Yuan-ti Pureblood",
    "Zombie",
    "Elf",
    "Dwarf",
    "Dragonborn",
    "Gnome",
    "Half-Elf",
    "Half-Ord",
    "Halfling",
    "Human",
    "Tiefling",
    "Tabaxi",
]


for monster in monster_list:
    user_query = f"""
only provide me a python dictionary for the following dnd 5e monster that includes the following information - make sure the python format is correct:
    {monster} = {{
    "Description" : "enter as appropriate",
    "Narrative" : "100 words as appropriate",
    "Background" : "100 words as appropriate",
    "History" : "100 words as appropriate",
    "Lore" : "enter as appropriate",
    "Encounter Odds Percentage" : "enter percentage",
    "Also Known By" : "enter as appropriate",
    "Physical Features" : "enter as appropriate",
    "Location Found" : "enter as appropriate",
    "Sleeps" : "enter as appropriate",
    "Active During" : "enter as appropriate",
    "Role In Ecosystem" : "enter as appropriate",
    "Environmental Factors" : "enter as appropriate",
    "Habits" : "enter as appropriate",
    "Behavior" : "enter as appropriate",
    "Cultural Significance" : "enter as appropriate",
    "Worshiped By" : "enter as appropriate",
    "Worshiper Of" : "enter as appropriate",
    "Monster's Deity Or Patron" : "enter as appropriate",
    "Motivations" : "enter as appropriate",
    "Misconceptions" : "enter as appropriate",
    "Stereotypes" : "enter as appropriate",  
    "Commonly Mistake For" : "enter as appropriate",
    "Tactics If Alone" : "enter as appropriate",
    "Tactics Within A Group" : "enter as appropriate",
    "Group Dynamics" : "enter as appropriate",
    "Avoids" : "enter as appropriate",
    "Targets" : "enter as appropriate",
    "Commonly Found With" : [
        "list of other monster names as appropriate",
        "list of other monster names as appropriate",
        "etc...",
    ],
    "Travels In Groups" : "enter as appropriate",
    "Aggressiveness" : "enter as appropriate",
    "Do They Hunt Humans" : "enter as appropriate",
    "Strengths" : "any particular strengths the monster possess",
    "Weaknesses" : "any particular weaknesses the monster possess",
    "Are There Any Non-combat Approaches" : "enter as appropriate",
    "Pro-Tip Against Monster" : "tips on how to fight this monster",
    "Weapons Used" : [
        "enter as appropriate",
        "etc...",
    ],
    "Armor Used" : [
        "enter as appropriate",
        "etc...",
    ],
    "Items Used" : [
        "enter as appropriate",
        "etc...",
    ],
    "5 Random Facts" : [
        "enter as appropriate",
        "enter as appropriate",
        "enter as appropriate",
        "enter as appropriate",
        "enter as appropriate",
    ],
    "5 Common Treasure Drops" : [
        "list item as appropriate",
        "list item as appropriate",
        "list item as appropriate",
        "list item as appropriate",
        "list item as appropriate",
    ],
}}
    """

    chatgpt_response = query_chatgpt(openai_key,user_query)
    print(chatgpt_response)


    with open("./dnd_monster_update.py", "a") as file:
        file.write(chatgpt_response)
        file.write(",\n")

